# Generated by Django 6.1.1 on 2026-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ПВЗ')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долготоа')),
                ('base_price', models.DecimalField(decimal_places=2, default=150.0, max_digits=8, verbose_name='Базовые тарифная ставка (руб)')),
            ],
        ),
    ]
